//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Xamarin.Forms.Xaml.XamlResourceIdAttribute("FullSteamAhead-MVP0Project.Views.SignUpSignIn.SignUpPage.xaml", "Views/SignUpSignIn/SignUpPage.xaml", typeof(global::FullSteamAheadMVP0Project.Views.SignUpPage))]

namespace FullSteamAheadMVP0Project.Views {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("Views/SignUpSignIn/SignUpPage.xaml")]
    public partial class SignUpPage : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(SignUpPage));
        }
    }
}
