//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Xamarin.Forms.Xaml.XamlResourceIdAttribute("FullSteamAhead-MVP0Project.Views.StudentAccount.MyTeamsPage.xaml", "Views/StudentAccount/MyTeamsPage.xaml", typeof(global::FullSteamAheadMVP0Project.Views.MyTeamsPage))]

namespace FullSteamAheadMVP0Project.Views {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("Views/StudentAccount/MyTeamsPage.xaml")]
    public partial class MyTeamsPage : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private global::Xamarin.Forms.ListView MyTeams;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(MyTeamsPage));
            MyTeams = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.ListView>(this, "MyTeams");
        }
    }
}
